### ISSUE TITLE
Pytanie odnośnie kompetencji

### ISSUE THREAD

**Issue by Pabblittto** [Pabblittto/KisgDro69#1]
No panowie pytanko czysto kompetencyjne mające na celu ogarnięcie z kim pracuje:
ile to jest 2+2x2=?
Czekam na odpowiedzi.

**Comment by Xiguana** [comment]
a gdzie commity psychola

**Comment by Pabblittto** [comment]
noooooo właśnie chuja .... nie ma commitów :/  trzeba go do roboty zapędzić
Ale coś tam robił , kierowcą był  czy jak..luzik arbuzik, ewentualnie będziemy zapierdalać dzień i noc  😒

**Comment by Pabblittto** [comment]
Ej wiem że trochę brzmi jak ironia , te pytanie i ten kamień milowy to tak dla jaj zrobiłem, luzik,
# LUZIK KAPPA
